// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5bNPjFLPe_lV7giWCFxAYaNReIgvQUMo',
    appId: '1:447332240781:web:47201ed8eb1eed870a81c4',
    messagingSenderId: '447332240781',
    projectId: 'venue-booking-system-56ba7',
    authDomain: 'venue-booking-system-56ba7.firebaseapp.com',
    storageBucket: 'venue-booking-system-56ba7.appspot.com',
    measurementId: 'G-6TQK6MCMKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHk-tYkbmKVxlhvmNOfop0UQKYOFEVPw',
    appId: '1:447332240781:android:263a98c8b1f768c30a81c4',
    messagingSenderId: '447332240781',
    projectId: 'venue-booking-system-56ba7',
    storageBucket: 'venue-booking-system-56ba7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hC_tbdh1TJp0mYYhAIF7cdaX8_R4mC8',
    appId: '1:447332240781:ios:5d6c5ca963f84b450a81c4',
    messagingSenderId: '447332240781',
    projectId: 'venue-booking-system-56ba7',
    storageBucket: 'venue-booking-system-56ba7.appspot.com',
    iosClientId: '447332240781-vj8bicjhupejkrd0rsn5b4qdhcl0mulg.apps.googleusercontent.com',
    iosBundleId: 'com.example.venuebookingsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-hC_tbdh1TJp0mYYhAIF7cdaX8_R4mC8',
    appId: '1:447332240781:ios:5d6c5ca963f84b450a81c4',
    messagingSenderId: '447332240781',
    projectId: 'venue-booking-system-56ba7',
    storageBucket: 'venue-booking-system-56ba7.appspot.com',
    iosClientId: '447332240781-vj8bicjhupejkrd0rsn5b4qdhcl0mulg.apps.googleusercontent.com',
    iosBundleId: 'com.example.venuebookingsystem',
  );
}
